version: '3'
services:
  web:
    image: nginx:stable-alpine
    container_name: interconecta_frontend
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - secure_internal
    ports:
      - "8082:80"

networks:
  secure_internal:
    external: true
