name: 🚀 Deploy Frontend Interconecta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Desplegar Frontend en DO
    runs-on: ubuntu-latest

    steps:
      - name: Conectar y ejecutar script por SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash /opt/interconecta/deploy-frontend.sh

